### ISSUE TITLE
Career Section

### ISSUE THREAD

**Issue by smaranjitghose** [girlscript/geliose-mobility#3]
- Some illustration
- A quote about workplace 
- [Reference](https://www.jiosaavn.com/corporate/careers)
- Team Cards

**Comment by pallavithakare28** [comment]
May I work on this issue? It'll be great if you can assign it to me.

**Comment by pallavithakare28** [comment]
@smaranjitghose Thank you for assigning :) I'll soon make a PR.

**Comment by smaranjitghose** [comment]
> @smaranjitghose Thank you for assigning :) I'll soon make a PR.

Any updates @pallavithakare28 ? I am expecting your PR in a couple days.

**Comment by pallavithakare28** [comment]
@smaranjitghose Sorry for delay, but I am busy with exam so can't make PR now. It's ok for me if someone wants to work on this issue. Sorry for the inconvenience.
